weka:
	git add .
	git commit -m "advanced security features"
	git push

db:
	python manage.py makemigrations
	python manage.py migrate

all:
	python manage.py makemigrations
	python manage.py migrate
	python manage.py runserver 
